// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Nodecrypto = require("node:crypto");

Zora.test("Crypto", (function (t) {
        t.test("Hashing to sha256", (function (t) {
                var hash = Nodecrypto.createHash("sha256").update(Buffer.from("hash me")).digest("hex");
                t.equal("eb201af5aaf0d60629d3d2a61e466cfc0fedb517add831ecac5235e1daa963d6", hash, "");
              }));
        t.test("Hashing with key to sha256", (function (t) {
                var hash = Nodecrypto.createHmac("sha256", "secret").update(Buffer.from("hash me")).digest("hex");
                t.equal("832324d67f36f13c0ab0730000d4aaf469ff0983edcf170a9fdcaa22f6672fec", hash, "");
              }));
      }));

/*  Not a pure module */
