// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Nodeos = require("node:os");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

Zora.test("Os", (function (t) {
        t.test("Should be able to get the network interfaces", (function (t) {
                var ifaces = Nodeos.networkInterfaces();
                t.notEqual(Object.keys(ifaces).length, 0, "");
                t.equal(Belt_Option.isSome(Js_dict.get(ifaces, "lo")), true, "");
                var localhost = Belt_Array.getExn(Belt_Option.getExn(Js_dict.get(ifaces, "lo")), 0).address;
                t.equal(localhost, "127.0.0.1", "");
                console.log(ifaces);
              }));
      }));

/*  Not a pure module */
