// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Nodeos = require("node:os");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

Zora.test("Os", (function (t) {
        t.test("Should be able to get the network interfaces", (function (t) {
                var ifaces = Nodeos.networkInterfaces();
                t.notEqual(Object.keys(ifaces).length, 0, "");
                t.equal(Belt_Option.isSome(Js_dict.get(ifaces, "lo")), true, "");
              }));
      }));

/*  Not a pure module */
