// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Events = {};

var stdioPipe = [
  "pipe",
  "pipe",
  "pipe"
];

var stdioOverlapped = [
  "overlapped",
  "overlapped",
  "overlapped"
];

var stdioIgnore = [
  "ignore",
  "ignore",
  "ignore"
];

var stdioInherit = [
  "inherit",
  "inherit",
  "inherit"
];

exports.Events = Events;
exports.stdioPipe = stdioPipe;
exports.stdioOverlapped = stdioOverlapped;
exports.stdioIgnore = stdioIgnore;
exports.stdioInherit = stdioInherit;
/* No side effect */
