// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var Dirent = {};

var Dir = {};

var Stats = {};

var Constants = {};

var Flag = {};

var FileHandle = {};

var PromiseAPI = {};

function readdirWithFileTypes(dir) {
  return Fs.promises.readdir(dir, {
              withFileTypes: true
            });
}

var Impl = {};

var WriteStream = {
  Impl: Impl
};

var Impl$1 = {};

var ReadStream = {
  Impl: Impl$1
};

exports.Dirent = Dirent;
exports.Dir = Dir;
exports.Stats = Stats;
exports.Constants = Constants;
exports.Flag = Flag;
exports.FileHandle = FileHandle;
exports.PromiseAPI = PromiseAPI;
exports.readdirWithFileTypes = readdirWithFileTypes;
exports.WriteStream = WriteStream;
exports.ReadStream = ReadStream;
/* fs Not a pure module */
